using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Sstv.DomainExceptions.Discovery;

internal partial class ErrorCodeMethodCollector
{
    private const string GLOBAL = "global::";

    private static void GenerateSource(SourceProductionContext context,
        Dictionary<string, List<ErrorCodeInfo>> methodErrorCodes,
        Dictionary<string, List<string>> methodCalls,
        string namespaceName,
        string? className
    )
    {
        var keysToEmit = methodErrorCodes.Where(k => k.Value.Count > 0).Select(k => k.Key).ToList();

        if (keysToEmit.Count == 0)
        {
            return;
        }

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Collections.Frozen;");
        sb.AppendLine("using Sstv.DomainExceptions;");

        var allTypeNames = methodErrorCodes.Values
            .SelectMany(c => c)
            .Select(c => c.SourceTypeName)
            .OfType<string>()
            .Distinct()
            .Select(n =>
            {
                if (!n.StartsWith(GLOBAL, StringComparison.Ordinal) && n.Contains('.'))
                {
                    return GLOBAL + n;
                }

                return n;
            })
            .OrderBy(n => n)
            .ToArray();

        var allExtClassNames = methodErrorCodes.Values
            .SelectMany(c => c)
            .Select(c => c.ExtensionClassName)
            .OfType<string>()
            .Select(n =>
            {
                if (!n.StartsWith(GLOBAL, StringComparison.Ordinal) && n.Contains('.'))
                {
                    return GLOBAL + n;
                }

                return n;
            })
            .Distinct()
            .OrderBy(n => n)
            .ToArray();

        var aliasMap = new Dictionary<string, string>(StringComparer.Ordinal);
        var aliasCounts = new Dictionary<string, int>(StringComparer.Ordinal);

        foreach (var typeName in allTypeNames.Concat(allExtClassNames))
        {
            var lastDot = typeName.LastIndexOf('.');
            var simpleName = lastDot > 0
                ? typeName.Substring(lastDot + 1)
                : typeName;

            aliasCounts.TryGetValue(simpleName, out var count);
            aliasCounts[simpleName] = count + 1;

            var alias = count > 0 ? $"{simpleName}_{count}" : simpleName;
            aliasMap[typeName] = alias;
        }

        if (aliasMap.Count > 0)
        {
            sb.AppendLine();
        }

        foreach (var kvp in aliasMap)
        {
            sb.AppendLine($"using {kvp.Value} = {kvp.Key};");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");

        sb.AppendLine($"    public static partial class {className ?? "ErrorCodeMethodCollector"}");
        sb.AppendLine("    {");
        sb.AppendLine(
            "        public static readonly FrozenDictionary<string, ErrorCodeSource[]> ErrorCodesByMethod =");
        sb.AppendLine("            new Dictionary<string, ErrorCodeSource[]>");
        sb.AppendLine("            {");

        foreach (var key in keysToEmit)
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            var codes = string.Join(", ", methodErrorCodes[key].Select(c =>
            {
                var typeName = c.SourceTypeName;
                if (typeName != null && !typeName.StartsWith(GLOBAL, StringComparison.Ordinal) &&
                    typeName.Contains('.'))
                {
                    typeName = GLOBAL + typeName;
                }

                aliasMap.TryGetValue(typeName ?? "", out var typeAlias);

                var fullEnumExpression = c.FullEnumExpression;
                if (fullEnumExpression != null && typeAlias != null && fullEnumExpression.Contains('.'))
                {
                    var lastDot = fullEnumExpression.LastIndexOf('.');
                    var memberPart = fullEnumExpression.Substring(lastDot + 1);
                    fullEnumExpression = $"{typeAlias}.{memberPart}";
                }

                var extTypeName = c.ExtensionClassName;
                if (extTypeName != null && !extTypeName.StartsWith(GLOBAL, StringComparison.Ordinal) &&
                    extTypeName.Contains('.'))
                {
                    extTypeName = GLOBAL + extTypeName;
                }

                aliasMap.TryGetValue(extTypeName ?? "", out var extAlias);

                var typeArg = typeAlias is not null ? $", typeof({typeAlias})" : "";
                return c.SourceType == ErrorCodeSourceType.Enum
                    ? $"new ErrorCodeSource({extAlias}.GetErrorCode({fullEnumExpression ?? c.Code}), ErrorCodeSourceType.Enum{typeArg})"
                    : $"new ErrorCodeSource(\"{c.Code}\", ErrorCodeSourceType.Constant{typeArg})";
            }));
            sb.AppendLine($"                [\"{key}\"] = [{codes}],");
        }

        sb.AppendLine("            }.ToFrozenDictionary();");

        var callersToEmit = methodCalls
            .Where(k => k.Value.Count > 0 && methodErrorCodes.ContainsKey(k.Key))
            .Select(k => k.Key)
            .OrderBy(k => k)
            .ToList();

        sb.AppendLine();
        sb.AppendLine(
            "        public static readonly FrozenDictionary<string, string[]> MethodCallGraph =");
        sb.AppendLine("            new Dictionary<string, string[]>");
        sb.AppendLine("            {");

        foreach (var caller in callersToEmit)
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            var callees = string.Join("\", \"",
                methodCalls[caller].OrderBy(c => c).Select(EscapeString));
            sb.AppendLine($"                [\"{EscapeString(caller)}\"] = [\"{callees}\"],");
        }

        sb.AppendLine("            }.ToFrozenDictionary();");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("ErrorCodeMethodCollector.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string EscapeString(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}